// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/silfoxs/silgo/internal/pkg/database"
	"github.com/silfoxs/silgo/internal/pkg/logger"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	loggerLogger, cleanup, err := logger.New()
	if err != nil {
		return nil, nil, err
	}
	db, err := database.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	injector := &Injector{
		Logger: loggerLogger,
		Db:     db,
	}
	return injector, func() {
		cleanup()
	}, nil
}
